[workspace]
resolver = "2"
members = [".", "tools/common", "tools/installer", "tools/updater", "tools/launcher"]

# Version du jeu : c'est la SEULE à modifier pour changer de version
# (ex. 0.7.0). Sinon la CI augmente automatiquement le dernier chiffre.
[workspace.package]
version = "0.14.1"

[package]
name = "spacespore"
version.workspace = true
edition = "2021"

[dependencies]
spacespore-common = { path = "tools/common" }
bevy = { version = "0.15", features = ["wayland", "wav"] }
noise = "0.9"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
chrono = "0.4"
ureq = { version = "3", features = ["native-tls"], default-features = false }
zip = { version = "2", default-features = false, features = ["deflate"] }
igd-next = { version = "0.17.1", default-features = false }
arboard = "3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
